"""add is_staff to user

Revision ID: dd708950b433
Revises: 1a31ce608336
Create Date: 2025-02-13 18:47:21.049159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd708950b433'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=False, default=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###
